# Generated by Django 4.2.7 on 2023-11-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_rename_category_item_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
    ]
